workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 30
    scripts:
      - name: Generate Missing Wrapper
        script: |
          cd SnookerScoreCalculator
          gradle wrapper --gradle-version 8.5
      - name: Build Android App
        script: |
          cd SnookerScoreCalculator
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - SnookerScoreCalculator/app/build/outputs/apk/debug/*.apk